export {
  DAKINIS_URL_CORPORATE,
  DAKINIS_URL_CORE,
  DAKINIS_URL_HUB,
  DAKINIS_URL_LANDING,
  DAKINIS_URL_STREAMAUTOMATOR,
  DAKINIS_URL_AKOENET
} from "@dakinis/shared-brand";

export { DAKINIS_LANDING_PROJECTS } from "./landing-projects.js";
